apiVersion: v1
kind: Pod
metadata:
  name: nodejs-helloworld
spec:
  containers:
  - image: <dockerhub-username>/nodejs-helloworld
    imagePullPolicy: Always
    name: nodejs-helloworld
    resources:
      requests:
        memory: 1G
        cpu: 1
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
  dnsPolicy: ClusterFirst
  nodeName: aci-connector